"""NLE abstraction + DaVinci Resolve driver (script-generating, honest).

NLEDriver is substitutable (Premiere etc.). The Resolve driver does NOT
claim a live API connection: it generates real, documented scripts
(Python for the Resolve scripting API + Lua variant + human runbook + FCP7
XML timeline interchange) from the deterministic timeline.json, so an
editor can reproduce the assembly exactly. If DaVinci Resolve is installed,
`resolve_available()` reports it; execution itself stays human-triggered.
"""
from __future__ import annotations
import abc
import csv
import json
import os
import shutil
import xml.etree.ElementTree as ET


class NLEDriver(abc.ABC):
    name: str = "abstract"

    @abc.abstractmethod
    def export(self, timeline: dict, outdir: str, production_title: str = "") -> dict:
        """Write NLE artefacts into outdir. Return {'files': [...], 'notes': str}."""

    @abc.abstractmethod
    def available(self) -> bool:
        """True if the NLE is reachable for automated checks (not required)."""


def fcp7_xml(timeline: dict, title: str = "timeline") -> str:
    """Minimal FCP7 XML (xmeml) sequence for interchange with Resolve/Premiere."""
    fps = float(timeline.get("fps", 30))
    seq = ET.Element("xmeml", version="4")
    sequence = ET.SubElement(seq, "sequence", name=title)
    ET.SubElement(sequence, "rate").extend([_el("timebase", str(int(round(fps)))),
                                            _el("ntsc", "FALSE")])
    media = ET.SubElement(sequence, "media")
    video = ET.SubElement(media, "video")
    track = ET.SubElement(video, "track")
    for ev in timeline.get("events", []):
        ci = ET.SubElement(track, "clipitem", id=str(ev.get("cut_id", "")))
        ET.SubElement(ci, "name").text = str(ev.get("cut_id", ""))
        ET.SubElement(ci, "in").text = str(int(round(float(ev.get("timeline_in", 0)) * fps)))
        ET.SubElement(ci, "out").text = str(int(round(float(ev.get("timeline_out", 0)) * fps)))
        f = ET.SubElement(ci, "file", id=f"f-{ev.get('cut_id','')}")
        ET.SubElement(f, "name").text = str(ev.get("source", ""))
        ET.SubElement(f, "pathurl").text = str(ev.get("source", ""))
    return ET.tostring(seq, encoding="unicode")


def _el(tag: str, text: str) -> ET.Element:
    e = ET.Element(tag)
    e.text = text
    return e


RESOLVE_PY_TEMPLATE = '''"""Generated by Cuts Studio — DaVinci Resolve assembly script.
Run INSIDE DaVinci Resolve: Workspace > Console, or via
  fuscript (see RUNBOOK.md in this folder).

Timeline: {title} | fps {fps} | {n} events. Deterministic from timeline.json.
This script only creates bins/timeline/markers — it never publishes.
"""
import json, os

TIMELINE_JSON = r"{timeline_json}"
TARGET_FPS = {fps}
TIMELINE_NAME = "{title}"

def main():
    resolve = app.GetResolve() if "app" in dir() else None  # noqa: F821
    if resolve is None:
        print("Open this script inside DaVinci Resolve's Console (see RUNBOOK.md).")
        return False
    pm = resolve.GetProjectManager()
    project = pm.GetCurrentProject() or pm.CreateProject(TIMELINE_NAME)
    mp = project.GetMediaPool()
    tl = mp.CreateEmptyTimeline(TIMELINE_NAME)
    events = json.load(open(TIMELINE_JSON, encoding="utf-8"))["events"]
    for ev in events:
        mp.AppendToTimeline([{{"mediaPath": ev["source"],
                               "startFrame": 0,
                               "endFrame": max(1, int(ev["duration"] * TARGET_FPS))}}])
    print(f"Timeline '{{TIMELINE_NAME}}' assembled with {{len(events)}} events.")
    return True

if __name__ == "__main__":
    main()
'''

RESOLVE_LUA_TEMPLATE = '''-- Generated by Cuts Studio — Resolve Lua variant (Console > Lua).
local timeline_json = [[{timeline_json}]]
print("Import timeline JSON: " .. timeline_json)
print("Create timeline '{title}' at {fps} fps, then append {n} clips in order (see RUNBOOK.md).")
'''

RUNBOOK_TEMPLATE = '''# Resolve Runbook — {title}

Generated artefacts in this folder:

- `timeline.json` — deterministic source of truth (engine-owned)
- `timeline.xmeml` — FCP7 XML interchange (File > Import Timeline in Resolve)
- `resolve_assemble.py` — Console/Python assembly script
- `resolve_assemble.lua` — Console/Lua variant

Steps (Resolve free or Studio):

1. Place source VOD/POV files at the exact `source` paths from `timeline.json`
   (or relink on import).
2. Preferred: `File > Import > Timeline...` and pick `timeline.xmeml`.
3. Alternative: open Console (Workspace > Console), load `resolve_assemble.py`.
4. Verify durations against `timeline.json.total_seconds = {total}s`.
5. Render master per `09-composition/composition.md`, register it with
   `cstudio master <slug> --file <master>`.

Nothing here uploads or publishes. Publication stays gated by
`publish_lock + rights clearance + master + package`.
'''


class ResolveDriver(NLEDriver):
    name = "davinci-resolve"

    def available(self) -> bool:
        return bool(shutil.which("fuscript") or shutil.which("resolve")
                    or os.environ.get("RESOLVE_SCRIPT_API"))

    def export(self, timeline: dict, outdir: str, production_title: str = "") -> dict:
        os.makedirs(outdir, exist_ok=True)
        title = production_title or "timeline"
        fps = float(timeline.get("fps", 30))
        events = timeline.get("events", [])
        tj = os.path.join(outdir, "timeline.json")
        with open(tj, "w", encoding="utf-8") as fh:
            json.dump(timeline, fh, ensure_ascii=False, indent=2)
        with open(os.path.join(outdir, "timeline.xmeml"), "w", encoding="utf-8") as fh:
            fh.write(fcp7_xml(timeline, title))
        with open(os.path.join(outdir, "resolve_assemble.py"), "w", encoding="utf-8") as fh:
            fh.write(RESOLVE_PY_TEMPLATE.format(timeline_json=tj, fps=fps,
                                                title=title, n=len(events)))
        with open(os.path.join(outdir, "resolve_assemble.lua"), "w", encoding="utf-8") as fh:
            fh.write(RESOLVE_LUA_TEMPLATE.format(timeline_json=tj, title=title,
                                                 fps=fps, n=len(events)))
        with open(os.path.join(outdir, "RUNBOOK.md"), "w", encoding="utf-8") as fh:
            fh.write(RUNBOOK_TEMPLATE.format(title=title, total=timeline.get("total_seconds")))
        files = ["timeline.json", "timeline.xmeml", "resolve_assemble.py",
                 "resolve_assemble.lua", "RUNBOOK.md"]
        return {"files": files, "outdir": outdir,
                "notes": "Import xmeml or run console script; live API not assumed."}


DRIVERS = {"davinci-resolve": ResolveDriver}


def get_driver(name: str = "davinci-resolve") -> NLEDriver:
    try:
        return DRIVERS[name]()
    except KeyError:
        raise ValueError(f"unknown NLE driver: {name} (available: {sorted(DRIVERS)})")
